import { Chart, HStack, Image, ProgressView, RoundedRectangle, Spacer, Text, VStack, ZStack } from '@expo/ui/swift-ui';
import { containerBackground, font, foregroundStyle, frame, padding, progressViewStyle, tint } from '@expo/ui/swift-ui/modifiers';
import { createWidget, type WidgetEnvironment } from 'expo-widgets';
import type { DietWidgetSnapshot } from '@/domain/widget-snapshots';

const surface='#191C22', text='#F4F6FB', muted='#969FAD', blue='#719BFF', gold='#E5BB73', purple='#B69BFA';
function Header({ eyebrow=false }: { eyebrow?: boolean }) { 'widget'; return <HStack spacing={10}><ZStack><RoundedRectangle cornerRadius={10} modifiers={[frame({width:32,height:32}),foregroundStyle('#342F27')]} /><Image systemName="fork.knife" size={17} color={gold}/></ZStack><VStack alignment="leading" spacing={2}>{eyebrow?<Text modifiers={[font({size:10,weight:'medium'}),foregroundStyle(muted)]}>TODAY</Text>:null}<Text modifiers={[font({size:eyebrow?19:18,weight:'medium'}),foregroundStyle(text)]}>Diet</Text></VStack></HStack>; }
function Macro({name,value,goal,color}:{name:string;value:number;goal:number;color:string}){'widget';return <VStack alignment="leading" spacing={5}><HStack><Text modifiers={[font({size:13}),foregroundStyle(text)]}>{name}</Text><Spacer/><Text modifiers={[font({size:13,weight:'medium'}),foregroundStyle(color)]}>{value}{goal?` / ${goal}`:''} g</Text></HStack><ProgressView value={goal?Math.min(value/goal,1):0} modifiers={[progressViewStyle('linear'),tint(color)]}/></VStack>}
function Ring({p,medium=false}:{p:DietWidgetSnapshot;medium?:boolean}){'widget';const ratio=p.calorieGoal?Math.min(p.calories/p.calorieGoal,1):0;return <ZStack modifiers={[frame({width:medium?108:172,height:medium?108:172})]}><Chart data={[{x:'eaten',y:Math.max(ratio,.001),color:blue},{x:'left',y:Math.max(1-ratio,.001),color:'#30353F'}]} type="pie" pieStyle={{innerRadius:.84,angularInset:0}} modifiers={[frame({width:medium?108:172,height:medium?108:172})]}/><VStack spacing={3}><Text modifiers={[font({size:medium?25:34,weight:'medium',design:'rounded'}),foregroundStyle(text)]}>{p.calories.toLocaleString()}</Text><Text modifiers={[font({size:12}),foregroundStyle(muted)]}>{medium?'calories':`of ${p.calorieGoal.toLocaleString()} cal`}</Text></VStack></ZStack>}
function DietView(p:DietWidgetSnapshot,e:WidgetEnvironment){'widget';const left=Math.max(p.calorieGoal-p.calories,0);if(e.widgetFamily==='systemSmall')return <VStack alignment="leading" spacing={9} modifiers={[padding({all:17}),containerBackground(surface,'widget')]}><Header/><Spacer/><Text modifiers={[font({size:40,weight:'medium',design:'rounded'}),foregroundStyle(text)]}>{p.calories.toLocaleString()}</Text><Text modifiers={[font({size:13}),foregroundStyle(muted)]}>of {p.calorieGoal.toLocaleString()} calories</Text><HStack spacing={4}><RoundedRectangle cornerRadius={3} modifiers={[frame({width:48,height:5}),foregroundStyle(blue)]}/><RoundedRectangle cornerRadius={3} modifiers={[frame({width:60,height:5}),foregroundStyle(gold)]}/><RoundedRectangle cornerRadius={3} modifiers={[frame({width:34,height:5}),foregroundStyle(purple)]}/></HStack><Text modifiers={[font({size:12,weight:'medium'}),foregroundStyle(gold)]}>{left} remaining</Text></VStack>;
if(e.widgetFamily==='systemMedium')return <HStack spacing={20} modifiers={[padding({all:18}),containerBackground(surface,'widget')]}><VStack alignment="leading" spacing={10}><Header eyebrow/><Ring p={p} medium/></VStack><VStack alignment="leading" spacing={10}><Macro name="Protein" value={p.protein} goal={p.proteinGoal} color={blue}/><Macro name="Carbs" value={p.carbs} goal={p.carbsGoal} color={gold}/><Macro name="Fat" value={p.fat} goal={p.fatGoal} color={purple}/></VStack></HStack>;
return <VStack alignment="leading" spacing={16} modifiers={[padding({all:22}),containerBackground(surface,'widget')]}><Header eyebrow/><HStack spacing={22}><Ring p={p}/><VStack alignment="leading" spacing={17}><Macro name="Protein" value={p.protein} goal={p.proteinGoal} color={blue}/><Macro name="Carbs" value={p.carbs} goal={p.carbsGoal} color={gold}/><Macro name="Fat" value={p.fat} goal={p.fatGoal} color={purple}/></VStack></HStack><Spacer/><Text modifiers={[font({size:13}),foregroundStyle(muted)]}>{left} calories remaining</Text></VStack>}
export default createWidget('DietWidget',DietView);
