import { HStack,Image,ProgressView,RoundedRectangle,Spacer,Text,VStack,ZStack } from '@expo/ui/swift-ui';
import { containerBackground,font,foregroundStyle,frame,lineLimit,padding,progressViewStyle,tint } from '@expo/ui/swift-ui/modifiers';
import { createWidget,type WidgetEnvironment } from 'expo-widgets';
import type { MaxesWidgetSnapshot } from '@/domain/widget-snapshots';
const surface='#191C22',text='#F4F6FB',muted='#969FAD',blue='#719BFF',green='#71D7B1',gold='#E5BB73',purple='#B69BFA';
const colors=[purple,gold,blue,green];
function Header({eye,title='Maxes'}:{eye?:boolean;title?:string}){'widget';return <HStack spacing={10}><ZStack><RoundedRectangle cornerRadius={10} modifiers={[frame({width:32,height:32}),foregroundStyle('#302B42')]}/><Image systemName="dumbbell" size={17} color={purple}/></ZStack><VStack alignment="leading" spacing={2}>{eye?<Text modifiers={[font({size:10,weight:'medium'}),foregroundStyle(muted)]}>{title==='Maxes'?'CURRENT RECORDS':'STRONGEST LIFT'}</Text>:null}<Text modifiers={[font({size:19,weight:'medium'}),foregroundStyle(text),lineLimit(1)]}>{title}</Text></VStack></HStack>}
function MaxesView(p:MaxesWidgetSnapshot,e:WidgetEnvironment){'widget';const lifts=p.lifts.slice(0,4),strong=lifts[0],max=Math.max(Number(strong?.value||1),1);if(e.widgetFamily==='systemSmall')return <VStack alignment="leading" spacing={8} modifiers={[padding({all:17}),containerBackground(surface,'widget')]}><Header/><Spacer/>{lifts.map(l=><HStack key={l.name}><Text modifiers={[font({size:13}),foregroundStyle(muted),lineLimit(1)]}>{l.name.replace(' press','')}</Text><Spacer/><Text modifiers={[font({size:13,weight:'medium'}),foregroundStyle(text)]}>{l.value}</Text></HStack>)}</VStack>;
if(e.widgetFamily==='systemMedium')return <HStack spacing={18} modifiers={[padding({all:18}),containerBackground(surface,'widget')]}><VStack alignment="leading"><Header eye title={strong?.name||'No max yet'}/><Spacer/><HStack alignment="firstTextBaseline" spacing={4}><Text modifiers={[font({size:35,weight:'medium',design:'rounded'}),foregroundStyle(text)]}>{strong?.value||'—'}</Text><Text modifiers={[font({size:15}),foregroundStyle(muted)]}>{p.unit}</Text></HStack><Text modifiers={[font({size:13}),foregroundStyle(muted)]}>Logged {strong?.date||'—'}</Text></VStack><HStack alignment="bottom" spacing={12}>{lifts.map((l,i)=><VStack key={l.name} spacing={4}><Spacer/><RoundedRectangle cornerRadius={7} modifiers={[frame({width:35,height:Math.max(25,Number(l.value)/max*90)}),foregroundStyle(colors[i])]}/><Text modifiers={[font({size:9}),foregroundStyle(muted),lineLimit(1)]}>{l.name.slice(0,5)}</Text></VStack>)}</HStack></HStack>;
return <VStack alignment="leading" spacing={18} modifiers={[padding({all:22}),containerBackground(surface,'widget')]}><Header eye/>{lifts.map((l,i)=><HStack key={l.name} spacing={12}><Text modifiers={[font({size:14}),foregroundStyle(muted),frame({width:100})]}>{l.name.replace(' press','')}</Text><ProgressView value={Number(l.value)/max} modifiers={[progressViewStyle('linear'),tint(colors[i]),frame({width:170})]}/><Spacer/><Text modifiers={[font({size:18,weight:'medium'}),foregroundStyle(text)]}>{l.value}</Text></HStack>)}<Spacer/><Text modifiers={[font({size:13}),foregroundStyle(muted)]}>All values in {p.unit==='lb'?'pounds':'kilograms'} · all-rep records</Text></VStack>}
export default createWidget('MaxesWidget',MaxesView);
